import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Navbar from '@/components/layout/ui/Navbar'
import Providers from '@/libs/Providers'
import ToastProvider from '@/libs/ToastProvider'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Auth',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <Providers>
      <html lang="en">
        <body>
          <ToastProvider>
          {children}
          </ToastProvider>
        </body>
      </html>
    </Providers>
  )
}
